############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Projects"
url = "projects/"
weight = 3

[[main]]
name = "Blog"
hasChildren = true
weight = 4

[[main]]
parent = "Blog"
name = "Articles"
url = "blog/"

[[main]]
parent = "Blog"
name = "Authors"
url = "authors/"

[[main]]
parent = "Blog"
name = "Categories"
url = "categories/"

[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Credits"
url = "credits/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
